compile1:
# 	Compile your code for first part here
gcc process.c -o process
run1: compile1
# 	 Execute part 1 here
./process
compile2:
# 	Compile your code for second part here
gcc thread.c -o thread
run2: compile2
#	Execute part 2 here
./thread

